/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.norad

class Application {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(Application().greeting)
}
